### PR TITLE
Bump to 0.5.3

### PR DESCRIPTION
**Pull request by nh13**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by nh13** [comment]
@conda-forge-admin, please rerender

**Comment by nh13** [comment]
@sodre can you review as the maintainer?

**Comment by sodre** [comment]
@conda-forge-admin, please rerender

**Review by sodre — COMMENTED** [review]
LGTM, would you be interested in becoming a maintainer?

**Comment by SimonBoothroyd** [comment]
@sodre could we get this merged? Feel free to add me as a maintainer.

**Comment by SimonBoothroyd** [comment]
@conda-forge-admin

**Comment by SimonBoothroyd** [comment]
@conda-forge-admin, please rerender

**Comment by SimonBoothroyd** [comment]
This is likely superseded by #3

**Pull request closed without merging**
